version: "3.8"

x-relay: &x-relay
  build: .
  entrypoint: ["moq-relay"]
  environment:
    RUST_LOG: ${RUST_LOG:-debug}
  volumes:
  - ./dev/localhost.crt:/etc/tls/cert:ro
  - ./dev/localhost.key:/etc/tls/key:ro
  - certs:/etc/ssl/certs
  depends_on:
    install-certs:
      condition: service_completed_successfully

services:
  redis:
    image: redis:7
    ports:
    - "6400:6379"

  api:
    build: .
    volumes:
      - ./topo.yaml:/topo.yaml:ro
    entrypoint: moq-api
    command: --listen [::]:4440 --redis redis://redis:6379 --topo-path topo.yaml

  relay4441:
    <<: *x-relay
    command: --listen [::]:4441 --tls-cert /etc/tls/cert --tls-key /etc/tls/key --api http://api:4440 --api-node https://localhost:4441 --dev
    ports:
    - "4441:4441"
    - "4441:4441/udp"

  relay4443:
    <<: *x-relay
    command: --listen [::]:4443 --tls-cert /etc/tls/cert --tls-key /etc/tls/key --api http://api:4440 --api-node https://localhost:4443 --dev
    ports:
    - "4443:4443"
    - "4443:4443/udp"

  relay4444:
    <<: *x-relay
    command: --listen [::]:4444 --tls-cert /etc/tls/cert --tls-key /etc/tls/key --api http://api:4440 --api-node https://localhost:4444 --dev
    ports:
    - "4444:4444"
    - "4444:4444/udp"
  relay4445:
    <<: *x-relay
    command: --listen [::]:4445 --tls-cert /etc/tls/cert --tls-key /etc/tls/key --api http://api:4440 --api-node https://localhost:4445 --dev
    ports:
    - "4445:4445"
    - "4445:4445/udp"



  install-certs:
    image: golang:latest
    working_dir: /work
    command: go run filippo.io/mkcert -install
    environment:
      CAROOT: /work/caroot
    volumes:
    - ${CAROOT:-.}:/work/caroot
    - certs:/etc/ssl/certs
    - ./dev/go.mod:/work/go.mod:ro
    - ./dev/go.sum:/work/go.sum:ro

volumes:
  certs:
